### ISSUE TITLE
Export with V0.14.0 and --tla-str crashes

### ISSUE THREAD

**Issue by gokristian** [grafana/tanka#514]
Running this command with a parameter worked fine with version 0.13.0

> tk export environments/default k8s/ --tla-str foo=bar --merge --target Deployment/app

With version 0.14.0 and the paths switch 

> tk export k8s/ environments/default --tla-str foo=bar --merge --target Deployment/app

I get an error
```
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/grafana/tanka/pkg/jsonnet.Opts.Clone(0xc0003226f0, 0xc000322720, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/tanka-20210204-53513-1tcpv7x/pkg/jsonnet/eval.go:43 +0x1fa
github.com/grafana/tanka/pkg/tanka.parallelLoadEnvironments(0xc00032c5e0, 0x1, 0x1, 0xc0003226f0, 0xc000322720, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/tanka-20210204-53513-1tcpv7x/pkg/tanka/parallel.go:53 +0x253
github.com/grafana/tanka/pkg/tanka.ExportEnvironments(0xc00032c5e0, 0x1, 0x1, 0x7ffeefbff78a, 0x3, 0xc00014bcd0, 0x0, 0x1)
	/private/tmp/tanka-20210204-53513-1tcpv7x/pkg/tanka/export.go:60 +0x1f8
main.exportCmd.func2(0xc0001cd860, 0xc0001b8930, 0x2, 0x7, 0x0, 0x0)
	/private/tmp/tanka-20210204-53513-1tcpv7x/cmd/tk/export.go:101 +0x5de
github.com/go-clix/cli.(*Command).execute(0xc0001cd860, 0xc0001b88c0, 0x7, 0x7, 0xc0001cd860, 0xc0001b88c0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/go-clix/cli@v0.1.1/command.go:118 +0x2a3
github.com/go-clix/cli.(*Command).Execute(0xc0001acd20, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/go-clix/cli@v0.1.1/command.go:74 +0x154
main.main()
	/private/tmp/tanka-20210204-53513-1tcpv7x/cmd/tk/main.go:58 +0x2eb
```

Environment: mac OS Big Sur, Iterm2, brew installed Tanka

**Comment by morlay** [comment]
i have to use `-r` for hacking

**Comment by morlay** [comment]
https://github.com/grafana/tanka/blob/master/pkg/jsonnet/eval.go#L37

should be

```
extCode, tlaCode := InjectedCode{}, InjectedCode{}
```

**Comment by gokristian** [comment]
🎉 🙇

**Comment by Cicatrice** [comment]
Hello! Any chance the bugfix proposed by #519 get released ? It seems the [latest release](https://github.com/grafana/tanka/releases/tag/v0.14.0) is still affected by this issue.
Many thanks!
