### ISSUE TITLE
Panic when attempting to show and environment missing a spec.json

### ISSUE THREAD

**Issue by jdbaldry** [grafana/tanka#55]
Using 0.3.0 image with an existing environment from ksonnet.
Steps to reproduce: 
- Perform `tk init -f` in the existing ksonnet project.
- Create an environment with a valid jsonnet file but missing the spec.json.
- Perform `tk show <environment>`
Error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x882fd8]

goroutine 1 [running]:
github.com/grafana/tanka/pkg/kubernetes.(*Kubernetes).Reconcile(0x0, 0xc0018803f0, 0x0, 0x0, 0x0, 0xc00048bce8, 0x5b8175, 0xc0000b8500, 0xc00048bcc0, 0xa6f1af)
        /drone/src/pkg/kubernetes/kubernetes.go:67 +0x118
main.showCmd.func1(0xc0000ce500, 0xc000164e90, 0x1, 0x1)
        /drone/src/cmd/tk/workflow.go:145 +0x122
github.com/spf13/cobra.(*Command).execute(0xc0000ce500, 0xc00001e1a0, 0x1, 0x1, 0xc0000ce500, 0xc00001e1a0)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000ce000, 0xc000164e20, 0xc00011e270, 0x0)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /drone/src/cmd/tk/main.go:106 +0x43f
```
Not a huge dealio, and the proper init workflow works fine it's something I encountered looking to switchover from ks to tk.

**Comment by sh0rez** [comment]
Thanks! Will look into this
