### ISSUE TITLE
Segfault when running tk env

### ISSUE THREAD

**Issue by partcyborg** [grafana/tanka#833]
With the latest release (v0.24.0), running `tk env` causes tk to segfault

```
mwilder@mwilder-1 ~> tk --version
2023/04/13 15:14:15 tk version v0.24.0

mwilder@mwilder-1 ~> tk env
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x86deae]

goroutine 1 [running]:
main.main.func1.1(0xc0001b5100?, {0xf4f9b8, 0x0, 0x0})
	/drone/src/cmd/tk/main.go:37 +0xae
github.com/go-clix/cli.(*Command).execute(0xc0002abea0, {0xf4f9b8, 0x0, 0x0})
	/go/pkg/mod/github.com/go-clix/cli@v0.2.0/command.go:118 +0x32b
github.com/go-clix/cli.(*Command).Execute(0xc000267360)
	/go/pkg/mod/github.com/go-clix/cli@v0.2.0/command.go:76 +0xdf
main.main()
	/drone/src/cmd/tk/main.go:73 +0x26f
```

**Comment by julienduchesne** [comment]
Fixed in master. I have some other bugs to fix and will do a release near the end of the month probably
