### ISSUE TITLE
Tanka panics if non-string annotation values are passed

### ISSUE THREAD

**Issue by emirisman** [grafana/tanka#960]
Example manifest:
`  test: {
    ns: k.core.v1.namespace.new('test') + {
      metadata+: {
        annotations+: {
          testlabel: true,
        },
      },
    },
  },`
  
 show/apply commands both since annotation values can only be strings, but this is not clear since it simply panics instead of an error message.
```panic: interface conversion: error is *manifest.SchemaError, not process.ErrorPrimitiveReached

goroutine 1 [running]:
github.com/grafana/tanka/pkg/process.walkObj(0x14001b6f760?, 0x10?, {0x14001b6f760?, 0x1, 0x1})
        github.com/grafana/tanka/pkg/process/extract.go:92 +0x5c4
github.com/grafana/tanka/pkg/process.walkJSON({0x1011582e0?, 0x14000c9b380?}, 0x1400165cbc0?, {0x14001b6f760, 0x1, 0x1})
        github.com/grafana/tanka/pkg/process/extract.go:39 +0xcc
github.com/grafana/tanka/pkg/process.walkObj(0x14000c9b470?, 0x30?, {0x0?, 0x0, 0x0})
        github.com/grafana/tanka/pkg/process/extract.go:90 +0x4e8
github.com/grafana/tanka/pkg/process.walkJSON({0x1011582e0?, 0x14002904e10?}, 0x14001f688f0?, {0x0, 0x0, 0x0})
        github.com/grafana/tanka/pkg/process/extract.go:39 +0xcc
github.com/grafana/tanka/pkg/process.Extract({0x1011582e0, 0x14002904e10})
        github.com/grafana/tanka/pkg/process/extract.go:22 +0x44
github.com/grafana/tanka/pkg/process.Process({{0x140000a1de8, 0x12}, {0x140002091c0, 0xb}, {{0x140000d91fe, 0x13}, {0x140000d951e, 0x20}, 0x140001af710}, {{0x140000d95e0, ...}, ...}, ...}, ...)
        github.com/grafana/tanka/pkg/process/process.go:29 +0x48
github.com/grafana/tanka/pkg/tanka.LoadManifests(0x140001702a0, {0x1016cddc0, 0x0, 0x0})
        github.com/grafana/tanka/pkg/tanka/load.go:72 +0xa4
github.com/grafana/tanka/pkg/tanka.Load({0x16f2476a8?, 0x100bc3f88?}, {{0x0, 0x140001aeff0, 0x140001af020, {0x0, 0x0, 0x0}, {0x0, 0x0}, ...}, ...})
        github.com/grafana/tanka/pkg/tanka/load.go:30 +0x54
github.com/grafana/tanka/pkg/tanka.Show(...)
        github.com/grafana/tanka/pkg/tanka/workflow.go:249
main.showCmd.func1(0x16f2476c8?, {0x140001fe360, 0x1, 0x9?})
        github.com/grafana/tanka/cmd/tk/workflow.go:293 +0x178
main.addCommandsWithLogLevelOption.func1(0x140000c6700?, {0x140001fe360, 0x1, 0x2})
        github.com/grafana/tanka/cmd/tk/main.go:77 +0xcc
github.com/go-clix/cli.(*Command).execute(0x14000169b80, {0x140001fe320, 0x2, 0x2})
        github.com/go-clix/cli@v0.2.0/command.go:118 +0x2bc
github.com/go-clix/cli.(*Command).Execute(0x140001690e0)
        github.com/go-clix/cli@v0.2.0/command.go:76 +0xcc
main.main()
        github.com/grafana/tanka/cmd/tk/main.go:58 +0x1d0
```

**Comment by iainlane** [comment]
Should be fixed by #967 - feel free to give it a try if you like
